spring:
  application:
    name: config_server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services_configs
server:
  port: 8888
